### ISSUE TITLE
Refactor frontend architecture

### ISSUE THREAD

**Issue by victorchabbert** [joffrey-bion/seven-wonders#11]
Right now, all files are separated by functionality (containers, components, redux, etc)

I suggest that we refactor to group files by functionality.
eg:
```
src/
  |-features/
    |-gameBrowser/
      |-GameBrowserContainer.js
      |-ducks.js
      |-sagas.js
      |-{specific components for game browser}.js
    |-...
  |-layout/
    |-LayoutComponent.js
  |-shared/
    |-...
  |-utils/
```

**Comment by joffrey-bion** [comment]
Separating files in features is hard, because features overlap. It's easier (better?) to group files under themes that are less opinionated, with clearer borders.

I'd actually rather keep sagas separate from the rest, as it is completely orthogonal. They are a way to deal with side-effects through redux actions and therefore can be kept totally apart from the UI stuff. In fact, there is [a few things we could do](https://github.com/luxons/seven-wonders/issues/13) with the sagas.

Now, I also like to keep the redux stuff apart from the UI stuff. Reducers and actions are here to describe how the state can change, the UI components are separate. There is no 1-to-1 mapping between components and parts of the state, so why try to put a reducer togeter with some related components? There will be annoying overlaps, and choices to make between 2 folders all the time.

The only bastards are the containers, which contain both UI stuff and redux state access. Yet, I still believe they belong to the UI part, as they simply use the selectors provided by the redux part, in the way they see fit. And the same argument applies here: a connected container may use multiple parts of the state, no 1-1 mapping.
