### ISSUE TITLE
Allow "play discarded card" effect at game end

### ISSUE THREAD

**Issue by bfreiberg** [joffrey-bion/seven-wonders#36]
When Halicarnassus (B) plays the last card of age 3 to upgrade its wonder the game ends before a card from the discard pile can be chosen.

**Comment by joffrey-bion** [comment]
Thanks for reporting this issue, this is indeed supposed to be allowed, and if it doesn't work it's definitely a bug.

**Comment by joffrey-bion** [comment]
Reproduced with the following steps:

1. Use the wonder Halikarnassus (either A or B)
2. Upgrade a wonder level with special power "play discarded card" **as the last play of any age** (when only 2 cards are left in your hand)

Observed behaviour: the game proceeds to the next age's first turn

Expected behaviour: the player should be able to pick from the discarded pile before the military conflicts are executed and before the next age begins.
