### ISSUE TITLE
Bug: Buying resources with Olympia B-side

### ISSUE THREAD

**Issue by stevasale** [joffrey-bion/seven-wonders#49]
When playing as Olympia B-side, upon building the first wonder stage (buy neighbouring resources for one gold), it becomes impossible to buy more than two resource units of the same type from the same neighbour, even though the neighbour has more than enough available and the player has enough gold.

**Comment by joffrey-bion** [comment]
Hi, thanks again a lot for the detailed feedback.

Could you please be more specific about how you experience the problem?
Is the button to play the card greyed out?
What is the tooltip message when you hover the button that you can't click?

**Comment by joffrey-bion** [comment]
@stevasale don't bother looking for these details, I could reproduce the issue:

* current wonder Olympia B
* 1 level of wonder built (so the discount for primary resources was on)
* left player has no clay
* right neighbour has 2 clays available (1 by default because he has the Babylon wonder + 1 due to a "Clay Pool" card)
* player has 20 gold, 1 clay due to "Clay Pit", 1 wood due to Olympia's default resource (and another with "Timber Yard")

Result: player cannot play "Siege Workshop" (3 clay, 1 wood)

* button greyed out with reason: *"missing resources that even neighbours don't have"*
