### ISSUE TITLE
feature request: select neighbour from which to buy resources

### ISSUE THREAD

**Issue by stevasale** [joffrey-bion/seven-wonders#50]
The possibility to select from whom the resources are bought (when both neighbours have the resource) would be nice, as this could be used tactically and is the intended way as per the rules.

**Comment by joffrey-bion** [comment]
Thanks for your feedback! 

Yes, this feature was actually planned.
The server supports it, the game just lacks the UI to allow the player to choose.

I think this should be one of the highest priorities.

**Comment by joffrey-bion** [comment]
There might not be a need for complex UI interactions here, which I initially thought as picking different resources manually from neighbours.

Instead, `BestPriceCalculator` could be improved to return *all* possible transactions configurations instead of just the cheapest ones. There shouldn't be too many, as we only have 2 providers + self.

So a simple table-like popup could show multiple rows, each of them would be a set of transactions to perform with one or two neighbours, along with the price for each neighbour, and the total cost.

**Comment by stevasale** [comment]
This is one possibility, as long as the number of shown possibilities are limited.

For exemple, the cases where players A and B have the same combination of resources  X and Y could blow this up unnecessarily.
Then {buy resource X from A for 2 gold and buy resource Y from B for 2 gold} is identical to  {buy resource Y from A for 2 gold and buy resource X from B for 2 gold}. The more resources are needed, the more cases like this can occur.

An alternative could be to popup the needed/missing resources if both neighbours have it and then select only from which neighbour to buy from, under the condition that the cheapest solution is not unique. If the cheapest solution is unique, I would assume most players would also chose this option and the popup is not needed (or maybe there is some crazy strategic exemption where it would be beneficial to chose the more expensive solution to hinder a neighbour from getting gold ?)

**Comment by joffrey-bion** [comment]
> maybe there is some crazy strategic exemption where it would be beneficial to chose the more expensive solution to hinder a neighbour from getting gold ?

@stevasale I would assume so, I already witnessed this in an IRL game. Currently only the cheapest options are computed, but I believe it would be desirable to offer this possibility too. The game rules allow this so the online game should also allow it.

That being said, the options would of course be sorted by total price, cheapest on top (and maybe some sort of indicator for other options to clearly show they are more expensive).

> If the cheapest solution is unique, I would assume most players would also chose this option and the popup is not needed

Yes I had already the pop-up bypass in mind if there is no choice to make, that's a given (because the extra step is clearly annoying 😄 )

> the cases where players A and B have the same combination of resources X and Y could blow this up unnecessarily.

The biggest resource-hungry card takes 7 resources AFAIR. If both neighbours provide all 7 resources, it means we have to choose between 2^7 = 128 possibilities, which is indeed absolutely terrible.
But as you pointed out, the only choice we really have to make is not really betwen the exact resources bought to each neighbour, but rather the combination of "how much gold to left neighbour, and how much to right neighbour".
So I will definitely keep only one of each group of equivalent choices.
